# Generated by Django 3.2.7 on 2021-09-21 22:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_last_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 22, 42, 17, 178083, tzinfo=utc), verbose_name='last request'),
        ),
    ]
