# Generated by Django 3.2.7 on 2021-09-21 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_last_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_request',
        ),
    ]
