# Generated by Django 3.2.7 on 2021-09-21 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_account_last_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_request',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last request'),
        ),
    ]
