# Generated by Django 3.2.7 on 2021-09-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_liked',
            field=models.DateField(auto_now_add=True, verbose_name='date liked'),
        ),
    ]
